### ISSUE TITLE
[Firefox] UI is broken with many workspaces.

### ISSUE THREAD

**Issue by lisyoen** [webida/webida-dashboard#41]
Moved from https://github.com/webida/webida-client/issues/557

![dashboard_firefox](https://cloud.githubusercontent.com/assets/7767406/10361902/21b4535a-6de6-11e5-8fbf-6c4da34618a4.png)

**Comment by changgyun** [comment]
[[BUGFIX]UI is broken with many workspaces #67](https://github.com/webida/webida-dashboard/pull/67)
