### ISSUE TITLE
Profile information can not be changed to empty value.

### ISSUE THREAD

**Issue by cimfalab** [webida/webida-dashboard#59]
When I want to "Company" value to be cleared in the User Profile,
it can not be done because "Apply" button is disabled.

I don't think "Company" value is required/mandatory value.

Please check whether user profiles values are required.

**Comment by JUHYUNCHOI** [comment]
I deleted the value of 'Company'. Then, 'Apply' is enabled.
I think problem is a name section.

When I put Korean name in the name section, 'Apply' is not enabled. However, English makes 'Apply' button enabled. 

Please, check this out.
